name: Build and Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: ${{ secrets.REGISTRY_URL }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        working-directory: dist
        run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
